[profile.release]
lto = true
opt-level = "s"
panic = "abort"

[workspace]
members = [
    "async-requester-api",
    "hyperdriver",
    "lib/shared",
    "receiver-a",
    "receiver-a-api",
    "receiver-b",
    "receiver-b-api",
]
resolver = "2"
