[workspace]
resolver = "2"
members = [
    "async-requester",
    "hyperdriver",
    "async-receiver-a",
    "async-receiver-b",
    "async-receiver-c",
    "lib/shared",
]

[profile.release]
panic = "abort"
opt-level = "s"
lto = true
