interface async-requester {
    use standard.{address};

    increment-counter: func(target: address, value: s32, another-value: string, yet-another-value: f32) -> result<string, string>;
    increment-counter-two: func(target: address, value: f64, another-value: list<string>, yet-another-value: bool) -> result<list<s32>, string>;
    increment-counter-async: func(target: address, value: s32, name: string) -> result<string, string>;
    some-other-function: func(target: address, string-val: string, another-string-val: string) -> result<f32, string>;
    increment-counter-three: func(target: address, string-val: string) -> result<f32, string>;
    increment-counter-four: func(target: address, string-val: string) -> result<f32, string>;
}
