interface receiver-b {
    // This interface contains function signature definitions that will be used
    // by the hyper-bindgen macro to generate async function bindings.

    use standard.{address};

    record some-struct {
        field-one: string,
        field-two: s32,
        field-three: some-enum
    }

    variant some-enum {
        variant-one(string),
        variant-two(s32)
    }

    // Function signature for: hello (local)
    record hello-signature-local {
        target: address,
        struct-val: some-struct,
        returning: f32
    }
}
